### ISSUE TITLE
Milestone 1 deliverables

### ISSUE THREAD

**Issue by Linda-ui** [Linda-ui/orbital_HeBao#4]
**By Milestone 1**:
**README**:
- [x] Motivation
- [x] Level of Achievement
- [x] Project Scope
- [x] System Design
- [x] Instructions to Test
- [x] Development Plan

**Project**:
- [x] Proof of Concept

**Comment by Linda-ui** [comment]
Solved with 658d3f219474494c2c48b23471de283735d32301

**Comment by Linda-ui** [comment]
Milestone 2: "Shell script of easy testing" completed with cdcfb89b7782538211c20205252736e641f9702e
